spring:
  datasource:
    url: jdbc:h2:mem:resdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: temp
    password: strongpassword

  jpa:
    hibernate:
      ddl-auto: update        # Hibernate will auto-create/update tables
    show-sql: true
    defer-datasource-initialization: true   # ensures schema/data.sql run AFTER Hibernate
    properties:
      hibernate.format_sql: true

  sql:
    init:
      mode: always            # allows schema.sql and data.sql to load in dev

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080